//! Notifications — mako (spec 05 §5, roadmap 0.5.1).
//!
//! Omarchy wires the notification daemon through a chain of files:
//!
//! ```text
//! ~/.config/mako/config  ─symlink→  current/theme/mako.ini
//!                                    └ generated by omarchy-theme-refresh
//!                                      from  mako.ini.tpl  (built-in or user)
//! ```
//!
//! Studio never edits the generated `mako.ini` (a theme switch would blow it
//! away). Instead it materializes a *user* template at
//! `~/.config/omarchy/themed/mako.ini.tpl` — which Omarchy prefers over its
//! built-in one — shaped so behavior survives both a theme switch and an
//! `omarchy-update`:
//!
//!   1. `include=` the read-only upstream `core.ini` (inherit stock behavior),
//!   2. the theme colour placeholders (so `{{ foreground }}` theming still works),
//!   3. a Studio-managed block holding the user's behavior overrides + rules.
//!
//! Everything but the managed block is opaque to us and copied through verbatim.

use std::path::{Path, PathBuf};

use crate::configfs::{atomic_write, CommentStyle, ManagedBlock};
use crate::error::{Result, StudioError};
use crate::omarchy::{cmds, OmarchyPaths};

/// The Studio-owned region name inside the mako template.
fn behavior_block() -> ManagedBlock {
    ManagedBlock::new("mako-behavior", CommentStyle::Hash)
}

/// `~/.config/omarchy/themed/mako.ini.tpl` — the user template Studio owns.
pub fn tpl_path(paths: &OmarchyPaths) -> PathBuf {
    paths.config.join("themed/mako.ini.tpl")
}

/// `default/themed/mako.ini.tpl` — Omarchy's built-in template (read-only).
fn builtin_tpl(paths: &OmarchyPaths) -> PathBuf {
    paths.system.join("default/themed/mako.ini.tpl")
}

/// The read-only upstream behavior file the template includes.
fn core_ini(paths: &OmarchyPaths) -> PathBuf {
    paths.system.join("default/mako/core.ini")
}

/// `~/.config/mako/config` — the symlink Omarchy installs.
fn user_config_link(paths: &OmarchyPaths) -> PathBuf {
    paths
        .config
        .parent()
        .map(|c| c.join("mako/config"))
        .unwrap_or_else(|| PathBuf::from("mako/config"))
}

/// How the user's `~/.config/mako/config` is wired — Studio's editing strategy
/// depends on it (spec 05 §5 doctor degrade).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LinkState {
    /// The stock symlink into the theme — the template pipeline is in play.
    Symlink,
    /// The user replaced it with a real file; theming won't reach mako and
    /// Studio must edit that file directly.
    RealFile(PathBuf),
    /// No mako config present at all.
    Absent,
}

fn detect_link(paths: &OmarchyPaths) -> LinkState {
    let link = user_config_link(paths);
    match std::fs::symlink_metadata(&link) {
        Ok(meta) if meta.file_type().is_symlink() => LinkState::Symlink,
        Ok(_) => LinkState::RealFile(link),
        Err(_) => LinkState::Absent,
    }
}

/// The Studio-managed mako template: the opaque `base` (include + colours) plus
/// the current behavior body, if we've written one before.
pub struct MakoTpl {
    path: PathBuf,
    /// Everything outside our managed block — copied through untouched.
    base: String,
    /// The current managed behavior body, if the block already exists.
    body: Option<String>,
    /// Set when the symlink was replaced by a real file (degraded mode).
    pub degraded: Option<PathBuf>,
}

impl MakoTpl {
    /// Load the current template state, seeding a fresh `base` from the built-in
    /// template (or a safe fallback) when the user template doesn't exist yet.
    pub fn load(paths: &OmarchyPaths) -> Self {
        let path = tpl_path(paths);
        let degraded = match detect_link(paths) {
            LinkState::RealFile(f) => Some(f),
            _ => None,
        };
        let block = behavior_block();
        let (base, body) = match std::fs::read_to_string(&path) {
            Ok(text) => (
                block.remove(&text),
                block.extract(&text).map(str::to_string),
            ),
            Err(_) => (seed_base(paths), None),
        };
        Self {
            path,
            base: base.trim_end_matches('\n').to_string(),
            body,
            degraded,
        }
    }

    /// The current behavior body, or an empty string if none is written yet.
    pub fn body(&self) -> &str {
        self.body.as_deref().unwrap_or("")
    }

    /// The template path Studio writes to.
    pub fn path(&self) -> &Path {
        &self.path
    }

    /// Render the full template with `body` spliced into the managed block —
    /// without writing it (used by tests and previews).
    pub fn render(&self, body: &str) -> String {
        let content = behavior_block().upsert(&format!("{}\n", self.base), body);
        if content.ends_with('\n') {
            content
        } else {
            format!("{content}\n")
        }
    }

    /// Write the template to disk with `body` as the managed behavior block.
    pub fn write(&self, body: &str) -> Result<()> {
        if let Some(parent) = self.path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| StudioError::External {
                cmd: format!("mkdir {}", parent.display()),
                detail: e.to_string(),
            })?;
        }
        atomic_write(&self.path, &self.render(body))
    }

    /// Write + regenerate `mako.ini` from the template + live-reload the daemon.
    /// `omarchy-theme-refresh` is the upstream pipeline (never ours); a failed
    /// `makoctl reload` is tolerated (mako may simply not be running yet).
    pub fn apply(&self, body: &str, runner: &dyn crate::cmd::CommandRunner) -> Result<()> {
        self.write(body)?;
        let out = runner.run(&cmds::theme_refresh())?;
        if !out.ok() {
            return Err(StudioError::External {
                cmd: "omarchy-theme-refresh".into(),
                detail: out.stderr.trim().to_string(),
            });
        }
        let _ = runner.run(&cmds::makoctl_reload());
        Ok(())
    }
}

/// Seed a fresh template `base` (include + colour placeholders). Prefer copying
/// the built-in template so we inherit whatever colours upstream themes on; fall
/// back to a minimal known-good template if it isn't present.
fn seed_base(paths: &OmarchyPaths) -> String {
    if let Ok(builtin) = std::fs::read_to_string(builtin_tpl(paths)) {
        // Strip a stray managed block if somehow present, keep the rest verbatim.
        return behavior_block().remove(&builtin);
    }
    let core = core_ini(paths);
    format!(
        "include={}\n\ntext-color={{{{ foreground }}}}\nborder-color={{{{ accent }}}}\nbackground-color={{{{ background }}}}\n",
        core.display()
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fake_paths(tag: &str) -> OmarchyPaths {
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .subsec_nanos();
        let root = std::env::temp_dir().join(format!(
            "omarchy-studio-mako-{tag}-{}-{nanos}",
            std::process::id()
        ));
        std::fs::create_dir_all(root.join(".config/omarchy/themed")).unwrap();
        std::fs::create_dir_all(root.join("sys/omarchy/default/themed")).unwrap();
        std::fs::create_dir_all(root.join("sys/omarchy/default/mako")).unwrap();
        OmarchyPaths {
            system: root.join("sys/omarchy"),
            config: root.join(".config/omarchy"),
            state: root.join(".local/state/omarchy"),
        }
    }

    fn write_builtin(paths: &OmarchyPaths) {
        std::fs::write(
            builtin_tpl(paths),
            "include=~/.local/share/omarchy/default/mako/core.ini\n\ntext-color={{ foreground }}\nborder-color={{ accent }}\nbackground-color={{ background }}\n",
        )
        .unwrap();
    }

    #[test]
    fn materializes_include_colours_and_managed_block() {
        let paths = fake_paths("materialize");
        write_builtin(&paths);

        let tpl = MakoTpl::load(&paths);
        assert_eq!(tpl.body(), ""); // nothing managed yet
        tpl.write("default-timeout=8000\n\n[urgency=critical]\nborder-color=#ff0000")
            .unwrap();

        let out = std::fs::read_to_string(tpl_path(&paths)).unwrap();
        // 1. inherits upstream behaviour
        assert!(out.contains("include=~/.local/share/omarchy/default/mako/core.ini"));
        // 2. theme colour placeholders survive → theming still works
        assert!(out.contains("text-color={{ foreground }}"));
        assert!(out.contains("border-color={{ accent }}"));
        // 3. our behaviour lives in a managed block
        assert!(out.contains("omarchy-studio:mako-behavior"));
        assert!(out.contains("default-timeout=8000"));
        assert!(out.contains("[urgency=critical]"));
    }

    #[test]
    fn round_trips_behaviour_and_preserves_base() {
        let paths = fake_paths("roundtrip");
        write_builtin(&paths);
        MakoTpl::load(&paths).write("default-timeout=3000").unwrap();

        // reload: base intact, body readable, colours untouched
        let re = MakoTpl::load(&paths);
        assert_eq!(re.body().trim(), "default-timeout=3000");
        assert!(re.base.contains("{{ foreground }}"));

        // rewriting replaces only the block, colours remain exactly once
        re.write("default-timeout=9000").unwrap();
        let out = std::fs::read_to_string(tpl_path(&paths)).unwrap();
        assert_eq!(out.matches("text-color={{ foreground }}").count(), 1);
        assert!(out.contains("default-timeout=9000"));
        assert!(!out.contains("default-timeout=3000"));
    }

    #[test]
    fn falls_back_when_no_builtin_template() {
        let paths = fake_paths("fallback");
        // no built-in tpl written
        let tpl = MakoTpl::load(&paths);
        let out = tpl.render("max-visible=3");
        assert!(out.contains("include="));
        assert!(out.contains("{{ foreground }}"));
        assert!(out.contains("max-visible=3"));
    }

    #[test]
    fn detects_a_real_file_replacing_the_symlink() {
        let paths = fake_paths("degraded");
        let link = user_config_link(&paths);
        std::fs::create_dir_all(link.parent().unwrap()).unwrap();
        std::fs::write(&link, "anchor=top-left\n").unwrap();
        let tpl = MakoTpl::load(&paths);
        assert_eq!(tpl.degraded, Some(link));
    }
}
